### ISSUE TITLE
Annotating with ANNOVAR after SPRINT results in some strandness confusion.

### ISSUE THREAD

**Issue by AlexPavlaras** [jumphone/SPRINT#10]
Hello,

I'm new to Bioinformatics, so excuse me in advance for any ambiguities I come up with. I used SPRINT to identify the RES for my RNA-seq samples and after that I used ANNOVAR to annotate the files produced by SPRINT (converted into ANNOVAR compatible format). I noticed though, that for many RES, ANNOVAR provided a different strand to the one SPRINT included in the results. My reads were pair-end. I used BWA 0.7.17 and samtools 1.2 with SPRINT. I guess aditional information is needed, so you can inform me about anything else I should provide you with, in order to solve this issue. 

Thank you for your time.

**Comment by jumphone** [comment]
Is your RNA-seq data "strand-specific" data ?
1. If your answer is "Yes", that means some RNA editing sites may occur on the antisense transcript (please see https://en.wikipedia.org/wiki/Antisense_RNA).
2. If your answer is "No", please don't believe the strand annotation of SPRINT. It just randomly assign "+" or "-".

**Comment by AlexPavlaras** [comment]
My RNA-seq data isn't strand-specific. In that case, should I consider only the strand annotation from ANNOVAR (Beacuse of the "random assignment" of SPRINT, should I ignore the strand annotations provided by it ?) As far as ncRNA is concerned, where + and - doesn't really apply, what is the meaning of + and - assigned by SPRINT ? As long as ANNOVAR can't assing + or - to these strands, is there a way to know if, for example, an A to G change in a non coding region is an ADAR one or a miscellaneous editing site ? 

Thank you in advance for your precious help and information.

**Comment by jumphone** [comment]
For A-to-I editing sites, the AG mismatch should be in “+” strand, while TC mismatch should be in “-“ strand.

For the A-to-I rate calculation, please see “Tip 5” in the README file.

Best,
Feng

**Comment by AlexPavlaras** [comment]
So, since my data isn't strand specific, as long as intergenic and ncRNA regions are concerned, where ANNOVAR doesn't provide strand annotation, I shouldn't use the "+" or "-" provided by SPRINT, right ?

**Comment by jumphone** [comment]
1. Please see "Tip 5", and think about the question: "how to calculate A-to-I rate".

2. If you trust the result of SPRINT and think all AG and TC mismatches are A-to-I editing sites, you can directly assign "+" to AG mismatch, and assign "-" to TC mismatch. 

3. If you don't want to directly assign "+" or "-", but want to use the annotation information derived from some database, you can annotate strand without using ANNOVAR:
step1: convert gene annotation file (includes ncRNA, GTF format) into BED format file
step2: use intersect function of BEDTOOLS to annotate each editing site.

Best,
Feng

**Comment by AlexPavlaras** [comment]
Thank you so much for your precious information. One last question: since I decided to use the "AG +/-" + "TC +/-" approach for my non strand-specific data, is there current knowledge regarding the FDR (False Discovery Rate) involded with this approach ?

**Comment by jumphone** [comment]
It's hard to define the true positive set, but current studies usually use A-to-G rate to evaluate their methods' performance. 

Since SPRINT doesn't only identify A-to-G changes, you can also use A-to-G rate to estimate the FDR (Tip 5). 

Best,
Feng

**Comment by fatimarasool** [comment]
Hi AlexPavlaras,

how you used ANNOVAR to annotate the files produced by SPRINT.?
how you convert the SPRINT output  into ANNOVAR compatible format?
