### ISSUE TITLE
sprint main errors 

### ISSUE THREAD

**Issue by fatimarasool** [jumphone/SPRINT#15]
Hi,
I have run this command as`sprint main -1 G1_forward_paired.fq -2 G1_reverse_paired.fq Triticum_aestivum.IWGSC.dna.toplevel.fa G1_ES bwa samtools`
samtool version is 1.9 and bwa tool version 0.7.17-t1188

but I met the following errors as

> [main] CMD: bwa samse -n4 Triticum_aestivum.IWGSC.dna.toplevel.fa G1_ES//tmp//genome/read2.sai G1_ES//tmp/cut_read2.fastq [main] Real time: 3829.614 sec; CPU: 3796.364 sec [bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files [bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files

and then 

> [E::hts_open_format] Failed to open file G1_ES//tmp//genome/name_read1_sorted.bam samtools merge: fail to open "G1_ES//tmp//genome/name_read1_sorted.bam": No such file or directory [E::hts_open_format] Failed to open file G1_ES//tmp//genome/all.bam samtools view: failed to open "G1_ES//tmp//genome/all.bam" for reading: No such file or directory cp: cannot stat 'G1_ES//tmp//genome/./all.sam': No such file or directory [E::hts_open_format] Failed to open file G1_ES//tmp//genome/all.bam samtools view: failed to open "G1_ES//tmp//genome/all.bam" for reading: No such file or directory
and then

> [E::hts_open_format] Failed to open file G1_ES//tmp//genome_mskAG/all.bam samtools view: failed to open "G1_ES//tmp//genome_mskAG/all.bam" for reading: No such file or directory cp: cannot stat 'G1_ES//tmp//genome_mskAG/./all.sam': No such file or directory [E::hts_open_format] Failed to open file G1_ES//tmp//genome_mskAG/all.bam samtools view: failed to open "G1_ES//tmp//genome_mskAG/all.bam" for reading: No such file or directory
 and then 
[E::hts_open_format] Failed to open file G1_ES//tmp//genome_mskTC/all.bam samtools view: failed to open "G1_ES//tmp//genome_mskTC/all.bam" for reading: No such file or directory cp: cannot stat 'G1_ES//tmp//genome_mskTC/./all.sam': No such file or directory [E::hts_open_format] Failed to open file G1_ES//tmp//genome_mskTC/all.bam samtools view: failed to open "G1_ES//tmp//genome_mskTC/all.bam" for reading: No such file or directory Traceback (most recent call last):

**Comment by jumphone** [comment]
Please try to use Samtools (version==1.2). You can download it from https://github.com/jumphone/SPRINT/tree/master/samtools_and_bwa
