### ISSUE TITLE
bwa "Permission denied" during prepare phase

### ISSUE THREAD

**Issue by bobo95110** [jumphone/SPRINT#16]
I encountered a problem during SPRINT prepare stage and I failed to resolve the question.
With bwa downloaded either from your github repo or I manually downloaded, after "Building BWA index...", I consistently get the "/bin/sh: 1: pathxxx Permission denied" message in my newly installed Ubuntu 19.04.
Hope you can kindly give me some clue to fix this issue.

**Comment by jumphone** [comment]
Please use “chmod” to change the permission. 

chmod 777 bwa

**Comment by bobo95110** [comment]
> Please use “chmod” to change the permission.
> 
> chmod 777 bwa

Sadly, after chmod I still get the same error. Still wondering why.

**Comment by jumphone** [comment]
Do you have permission to modify the directory of your FA file ?

You can copy the FA file to your own directory and then run SPRINT.

**Comment by bobo95110** [comment]
I do have permission to modify the directory. I can see several  msk/trans.fa file newly created.
The FA file is already in my own newly created directory.

**Comment by jumphone** [comment]
1. Can you show me the full error message?

2. Can you use BWA alone to build the index of your FA file? Please try to use bwa alone.

**Comment by bobo95110** [comment]
`Masking A with G in reference genome...
Masking T with C in reference genome...
Assembling transcripts...
Masking A with G in transcripts...
Masking T with C in transcripts...
Building BWA index...
/bin/sh: 1: samtools_and_bwa/: Permission denied
/bin/sh: 1: samtools_and_bwa/: Permission denied
/bin/sh: 1: samtools_and_bwa/: Permission denied
/bin/sh: 1: samtools_and_bwa/: Permission denied
/bin/sh: 1: samtools_and_bwa/: Permission denied
/bin/sh: 1: samtools_and_bwa/: Permission denied
`

I can use bwa alone to generate index.

**Comment by jumphone** [comment]
Can you show me your whole command line?

**Comment by bobo95110** [comment]
`cd /media/lab/Data2/SPRINT_File/

sprint prepare -t Mus_musculus.GRCm38.96.gtf Mus_musculus.GRCm38.dna.primary_assembly.fa samtools_and_bwa/
`
I put annotation, genome in the directory 'SPRINT_File'.

**Comment by jumphone** [comment]
Please change “samtools_and_bwa/” to “samtools_and_bwa/bwa”

**Comment by bobo95110** [comment]
This change solved my problem right away. Many thanks for your prompt reply.

**Comment by iqraishtiaq** [comment]
I am also facing same error kindly guide me 
`

> iqra@work-station:~/Documents$ sprint` prepare GCF_002263795.1_ARS-UCD1.2_genomic.fa bwa-0.7.12/bwa
> 
> ##############################################################################################
> 
>    SPRINT: SNP-free RNA editing Identification Toolkit
> 
>    http://sprint.tianlab.cn/SPRINT/
> 
>    Please contact 15110700005@fudan.edu.cn when questions arise.
> 
> ##############################################################################################
> Masking A with G in reference genome...
> Masking T with C in reference genome...
> Building BWA index...
> /bin/sh: 1: bwa-0.7.12/bwa: not found
> /bin/sh: 1: bwa-0.7.12/bwa: not found
> /bin/sh: 1: bwa-0.7.12/bwa: not found

> `found`

**Comment by jumphone** [comment]
> I am also facing same error kindly guide me
> `
> 
> > iqra@work-station:~/Documents$ sprint` prepare GCF_002263795.1_ARS-UCD1.2_genomic.fa bwa-0.7.12/bwa
> > ##############################################################################################
> > SPRINT: SNP-free RNA editing Identification Toolkit
> > http://sprint.tianlab.cn/SPRINT/
> > Please contact [15110700005@fudan.edu.cn](mailto:15110700005@fudan.edu.cn) when questions arise.
> > ##############################################################################################
> > Masking A with G in reference genome...
> > Masking T with C in reference genome...
> > Building BWA index...
> > /bin/sh: 1: bwa-0.7.12/bwa: not found
> > /bin/sh: 1: bwa-0.7.12/bwa: not found
> > /bin/sh: 1: bwa-0.7.12/bwa: not found
> 
> > `found`

Hi,

Maybe “bwa-0.7.12/bwa” is not in your working path. Could you please try the full path, such as “/home/xxx/bwa-0.7.12/bwa”.

Feng

**Comment by iqraishtiaq** [comment]
> > I am also facing same error kindly guide me
> > `
> > > iqra@work-station:~/Documents$ sprint` prepare GCF_002263795.1_ARS-UCD1.2_genomic.fa bwa-0.7.12/bwa
> > > ##############################################################################################
> > > SPRINT: SNP-free RNA editing Identification Toolkit
> > > http://sprint.tianlab.cn/SPRINT/
> > > Please contact [15110700005@fudan.edu.cn](mailto:15110700005@fudan.edu.cn) when questions arise.
> > > ##############################################################################################
> > > Masking A with G in reference genome...
> > > Masking T with C in reference genome...
> > > Building BWA index...
> > > /bin/sh: 1: bwa-0.7.12/bwa: not found
> > > /bin/sh: 1: bwa-0.7.12/bwa: not found
> > > /bin/sh: 1: bwa-0.7.12/bwa: not found
> > 
> > 
> > > `found`
> 
> Hi,
> 
> Maybe “bwa-0.7.12/bwa” is not in your working path. Could you please try the full path, such as “/home/xxx/bwa-0.7.12/bwa”.
> 
> Feng

Hi 
I have tried full path but always facing this issue "permission denied"
Refernce genome and bwa-0.7.12 both are placed in documents directory.

iqra@work-station:~/Documents$ sprint prepare Buffalo_reference_genome.fa /home/iqra/Documents/bwa-0.7.12

> Masking A with G in reference genome...
> Masking T with C in reference genome...
> Building BWA index...
> /bin/sh: 1: /home/iqra/Documents/bwa-0.7.12: Permission denied
> /bin/sh: 1: /home/iqra/Documents/bwa-0.7.12: Permission denied/bin/sh: 1: 
> /home/iqra/Documents/bwa-0.7.12: Permission denied

**Comment by iqraishtiaq** [comment]
Both commands are not working 
iqra@work-station:~/Documents$ sprint prepare Buffalo_reference_genome.fa /home/iqra/Documents/bwa-0.7.12/bwa
Masking A with G in reference genome...
Masking T with C in reference genome...
Building BWA index...
/bin/sh: 1: /home/iqra/Documents/bwa-0.7.12/bwa: not found
/bin/sh: 1: /home/iqra/Documents/bwa-0.7.12/bwa: not found
/bin/sh: 1: /home/iqra/Documents/bwa-0.7.12/bwa: not found

**Comment by jumphone** [comment]
> Both commands are not working
> iqra@work-station:~/Documents$ sprint prepare Buffalo_reference_genome.fa /home/iqra/Documents/bwa-0.7.12/bwa
> Masking A with G in reference genome...
> Masking T with C in reference genome...
> Building BWA index...
> /bin/sh: 1: /home/iqra/Documents/bwa-0.7.12/bwa: not found
> /bin/sh: 1: /home/iqra/Documents/bwa-0.7.12/bwa: not found
> /bin/sh: 1: /home/iqra/Documents/bwa-0.7.12/bwa: not found

Please check following issues:

1. Your system should support BWA (Centos, Ubuntu, Macs ...). Windows may not work.

2. If your system is based on UNIX, please use "chmod " to change the permission of BWA :

chmod     777      /home/iqra/Documents/bwa-0.7.12/bwa

3.  Could you please try to use BWA alone? You may need to test BWA alone before using SPRINT. 

Please check:  http://bio-bwa.sourceforge.net/bwa.shtml

Best,
Feng
