### ISSUE TITLE
Error in Fetching A2I RES's from Sprint output

### ISSUE THREAD

**Issue by iqraishtiaq** [jumphone/SPRINT#17]
I have run A2I.py script download from github.The command is as 
`python A2I.py 1 ~/iQRA/sabih/G1oldversion_result/SPRINT_identified_regular.res A_to_I_OUT`

I got the following error

> $1: INT, 1 for strand-specific sequencing data. 
$2: OUTPUT_DIR of SPRINT
$3: OUTPUT_PATH of A-to-G RESs

Traceback (most recent call last):
  File "A2I.py", line 15, in <module>
    fi=open(regular)
IOError: [Errno 20] Not a directory: '/home/ngslab/iQRA/sabih/G1oldversion_result/SPRINT_identified_regular.res/SPRINT_identified_regular.res'

**Comment by jumphone** [comment]
The command line should be:

python A2I.py 1 ~/iQRA/sabih/G1oldversion_result A_to_I_OUT
