### ISSUE TITLE
#

### ISSUE THREAD

**Issue by iqraishtiaq** [jumphone/SPRINT#18]

**Comment by jumphone** [comment]
Please try:

cut -f 3 SPRINT_identified_all.res > SPRINT_identified_all.res.col3

bedtools intersect -a SPRINT_identified_all.res.col3 -b wheat.bed -u

**Comment by iqraishtiaq** [comment]
`ERROR: file SPRINT_identified_all.res.col3 has non positional records, which are only valid for the groupBy tool.`

**Comment by jumphone** [comment]
Please try:

cut -f 1,2,3 SPRINT_identified_all.res > SPRINT_identified_all.res.col3

bedtools intersect -a SPRINT_identified_all.res.col3 -b wheat.bed -u

If it doesn’t work, can you send me some lines of your files using Email?

Feng

**Comment by iqraishtiaq** [comment]
bedtools intersect -a SPRINT_identified_all.res.col3 -b wheat.bed -u
ERROR: Received illegal bin number 37458 from getBin call.
ERROR: Unable to add record to tree.

Head SPRINT_identified_all.res.col3
1A    135397    135398
1A    135420    135421
1A    135429    135430
1A    135446    135447
1A    135450    135451
1A    11664892    11664893
1A    11664901    11664902
1A    11664961    11664962
1A    11665022    11665023
1A    11665066    11665067


 head SPRINT_identified_all.res
#Chrom    Start(0base)    End(1base)    Type    Supporting_reads
Strand    AD:DP
1A    135397    135398    CT    2    +    2:75
1A    135420    135421    CT    1    +    1:181
1A    135429    135430    CT    1    +    1:193
1A    135446    135447    CT    1    +    2:208
1A    135450    135451    CT    1    +    1:206
1A    11664892    11664893    GA    1    +    7:31
1A    11664901    11664902    GA    1    +    16:42
1A    11664961    11664962    GA    3    +    35:94
1A    11665022    11665023    GA    5    +    34:107



 head wheat.bed
1A    199    1683    .    .    +    Ensembl_Plants    exon    .    gene_id
"ENSRNA050013875"; transcript_id "ENSRNA050013875-T1"; exon_number "1";
gene_name "LSU_rRNA_eukarya"; gene_source "Ensembl_Plants"; gene_biotype
"rRNA"; transcript_source "Ensembl_Plants"; transcript_biotype "rRNA";
exon_id "ENSRNA050013875-E1";
1A    199    1683    .    .    +    Ensembl_Plants    gene    .    gene_id
"ENSRNA050013875"; gene_name "LSU_rRNA_eukarya"; gene_source
"Ensembl_Plants"; gene_biotype "rRNA";
1A    199    1683    .    .    +    Ensembl_Plants    transcript
.gene_id "ENSRNA050013875"; transcript_id "ENSRNA050013875-T1"; gene_name
"LSU_rRNA_eukarya"; gene_source "Ensembl_Plants"; gene_biotype "rRNA";
transcript_source "Ensembl_Plants"; transcript_biotype "rRNA";
1A    5022    6833    .    .    +    Ensembl_Plants    exon    .    gene_id
"ENSRNA050013847"; transcript_id "ENSRNA050013847-T1"; exon_number "1";
gene_name "SSU_rRNA_eukarya"; gene_source "Ensembl_Plants"; gene_biotype
"rRNA"; transcript_source "Ensembl_Plants"; transcript_biotype "rRNA";
exon_id "ENSRNA050013847-E1";
1A    5022    6833    .    .    +    Ensembl_Plants    gene    .    gene_id
"ENSRNA050013847"; gene_name "SSU_rRNA_eukarya"; gene_source
"Ensembl_Plants"; gene_biotype "rRNA";
1A    5022    6833    .    .    +    Ensembl_Plants    transcript
.gene_id "ENSRNA050013847"; transcript_id "ENSRNA050013847-T1"; gene_name
"SSU_rRNA_eukarya"; gene_source "Ensembl_Plants"; gene_biotype "rRNA";
transcript_source "Ensembl_Plants"; transcript_biotype "rRNA";
1A    7059    7215    .    .    +    Ensembl_Plants    exon    .    gene_id
"ENSRNA050013913"; transcript_id "ENSRNA050013913-T1"; exon_number "1";
gene_name "5_8S_rRNA"; gene_source "Ensembl_Plants"; gene_biotype "rRNA";
transcript_source "Ensembl_Plants"; transcript_biotype "rRNA"; exon_id
"ENSRNA050013913-E1";
1A    7059    7215    .    .    +    Ensembl_Plants    gene    .    gene_id
"ENSRNA050013913"; gene_name "5_8S_rRNA"; gene_source "Ensembl_Plants";
gene_biotype "rRNA";
1A    7059    7215    .    .    +    Ensembl_Plants    transcript
.gene_id "ENSRNA050013913"; transcript_id "ENSRNA050013913-T1"; gene_name
"5_8S_rRNA"; gene_source "Ensembl_Plants"; gene_biotype "rRNA";
transcript_source "Ensembl_Plants"; transcript_biotype "rRNA";
1A    12316    13827    .    .    +    Ensembl_Plants    exon    .
gene_id "ENSRNA050013874"; transcript_id "ENSRNA050013874-T1"; exon_number
"1"; gene_name "LSU_rRNA_eukarya"; gene_source "Ensembl_Plants";
gene_biotype "rRNA"; transcript_source "Ensembl_Plants"; transcript_biotype
"rRNA"; exon_id "ENSRNA050013874-E1";

Kindly solve my problem. I'll be very thankful to you.

**Comment by iqraishtiaq** [comment]
> Please try:
> 
> cut -f 1,2,3 SPRINT_identified_all.res > SPRINT_identified_all.res.col3
> 
> bedtools intersect -a SPRINT_identified_all.res.col3 -b wheat.bed -u
> 
> If it doesn’t work, can you send me some lines of your files using Email?
> 
> Feng

hi sir i have sent you all the files

**Comment by iqraishtiaq** [comment]
> Please try:
> 
> cut -f 1,2,3 SPRINT_identified_all.res > SPRINT_identified_all.res.col3
> 
> bedtools intersect -a SPRINT_identified_all.res.col3 -b wheat.bed -u
> 
> If it doesn’t work, can you send me some lines of your files using Email?
> 
> Feng

Sir, I have sent you headers of my All files. waiting for your reply. Kindly reply me.

**Comment by jumphone** [comment]
Have you tried to use the wheat.bed to annotated other files. Can you change it into a standard BED format file?

**Comment by iqraishtiaq** [comment]
No i haven't tried wheat.bed on others files

**Comment by iqraishtiaq** [comment]
I don't know how to change it into standard bed file.

**Comment by jumphone** [comment]
BED file should be TAB delimited.

Demo:

1A     7058     7215    GENE    ID   STRAND

**Comment by iqraishtiaq** [comment]
Can you guide me how i can convert  it into this format ?

**Comment by iqraishtiaq** [comment]
I have converted gtf file into bed.
please check it either it's useful or not ??

` head wheat.bed
1A	199	1683	ENSRNA050013875-T1	0	+	199	1683	01	1484,	0,
1A	5022	6833	ENSRNA050013847-T1	0	+	5022	6833	01	1811,	0,
1A	7059	7215	ENSRNA050013913-T1	0	+	7059	7215	01	156,	0,
1A	12316	13827	ENSRNA050013874-T1	0	+	12316	13827	01	1511,	0,
1A	15321	16832	ENSRNA050013873-T1	0	+	15321	16832	01	1511,	0,
1A	20008	21818	ENSRNA050013836-T1	0	+	20008	21818	01	1810,	0,
1A	22044	22200	ENSRNA050013914-T1	0	+	22044	22200	01	156,	0,
1A	28455	30266	ENSRNA050013853-T1	0	+	28455	30266	01	1811,	0,
1A	30492	30648	ENSRNA050013918-T1	0	+	30492	30648	01	156,	0,
1A	37092	38903	ENSRNA050013860-T1	0	+	37092	38903	01	1811,	0,
`

**Comment by iqraishtiaq** [comment]
> BED file should be TAB delimited.
> 
> Demo:
> 
> 1A 7058 7215 GENE ID STRAND

I have converted gtf file into bed.
please check it either it's useful or not ??

> head wheat.bed
1A 199 1683 ENSRNA050013875-T1 0 + 199 1683 01 1484, 0,
1A 5022 6833 ENSRNA050013847-T1 0 + 5022 6833 01 1811, 0,
1A 7059 7215 ENSRNA050013913-T1 0 + 7059 7215 01 156, 0,
1A 12316 13827 ENSRNA050013874-T1 0 + 12316 13827 01 1511, 0,
1A 15321 16832 ENSRNA050013873-T1 0 + 15321 16832 01 1511, 0,
1A 20008 21818 ENSRNA050013836-T1 0 + 20008 21818 01 1810, 0,
1A 22044 22200 ENSRNA050013914-T1 0 + 22044 22200 01 156, 0,
1A 28455 30266 ENSRNA050013853-T1 0 + 28455 30266 01 1811, 0,
1A 30492 30648 ENSRNA050013918-T1 0 + 30492 30648 01 156, 0,
1A 37092 38903 ENSRNA050013860-T1 0 + 37092 38903 01 1811, 0,

**Comment by jumphone** [comment]
Please try to use this bed: 

cut -f 1,2,3,4,5,6 wheat.bed > wheat_col6.bed

bedtools intersect -a SPRINT_identified_all.res.col3 -b wheat_col6.bed -wa -wb > output.bed

**Comment by iqraishtiaq** [comment]
> BED file should be TAB delimited.
> 
> Demo:
> 
> 1A 7058 7215 GENE ID STRAND

I have converted gtf file into bed.
please check it either it's useful or not ??

> head wheat.bed
1A 199 1683 ENSRNA050013875-T1 0 + 199 1683 01 1484, 0,
1A 5022 6833 ENSRNA050013847-T1 0 + 5022 6833 01 1811, 0,
1A 7059 7215 ENSRNA050013913-T1 0 + 7059 7215 01 156, 0,
1A 12316 13827 ENSRNA050013874-T1 0 + 12316 13827 01 1511, 0,
1A 15321 16832 ENSRNA050013873-T1 0 + 15321 16832 01 1511, 0,
1A 20008 21818 ENSRNA050013836-T1 0 + 20008 21818 01 1810, 0,
1A 22044 22200 ENSRNA050013914-T1 0 + 22044 22200 01 156, 0,
1A 28455 30266 ENSRNA050013853-T1 0 + 28455 30266 01 1811, 0,
1A 30492 30648 ENSRNA050013918-T1 0 + 30492 30648 01 156, 0,
1A 37092 38903 ENSRNA050013860-T1 0 + 37092 38903 01 1811, 0,

**Comment by iqraishtiaq** [comment]
> BED file should be TAB delimited.
> 
> Demo:
> 
> 1A 7058 7215 GENE ID STRAND

I have converted gtf file into bed.
please check it either it's useful or not ??

> head wheat.bed
1A 199 1683 ENSRNA050013875-T1 0 + 199 1683 01 1484, 0,
1A 5022 6833 ENSRNA050013847-T1 0 + 5022 6833 01 1811, 0,
1A 7059 7215 ENSRNA050013913-T1 0 + 7059 7215 01 156, 0,
1A 12316 13827 ENSRNA050013874-T1 0 + 12316 13827 01 1511, 0,
1A 15321 16832 ENSRNA050013873-T1 0 + 15321 16832 01 1511, 0,
1A 20008 21818 ENSRNA050013836-T1 0 + 20008 21818 01 1810, 0,
1A 22044 22200 ENSRNA050013914-T1 0 + 22044 22200 01 156, 0,
1A 28455 30266 ENSRNA050013853-T1 0 + 28455 30266 01 1811, 0,
1A 30492 30648 ENSRNA050013918-T1 0 + 30492 30648 01 156, 0,
1A 37092 38903 ENSRNA050013860-T1 0 + 37092 38903 01 1811, 0,

**Comment by iqraishtiaq** [comment]
> Please try to use this bed:
> 
> cut -f 1,2,3,4,5,6 wheat.bed > wheat_col6.bed
> 
> bedtools intersect -a SPRINT_identified_all.res.col3 -b wheat_col6.bed -wa -wb > output.bed

sir,I have run both commands but facing same error.

> bedtools intersect -a SPRINT_identified_all.res.col3 -b wheat_col6.bed -wa -wb > output.bed
ERROR: Received illegal bin number 37458 from getBin call.
ERROR: Unable to add record to tree.

**Comment by iqraishtiaq** [comment]
Kindly reply me ...how i can solve this error ???

**Comment by jumphone** [comment]
Please see 

https://github.com/arq5x/bedtools2/issues/656

Maybe you need to sort your two bed files

**Comment by iqraishtiaq** [comment]
I have sorted both files and then faced the same error

**Comment by jumphone** [comment]
Can you try BEDOPS?

bedops --intersect a.bed b.bed > output.bed

**Comment by iqraishtiaq** [comment]
> bedtools intersect -wa -wb -a wheat_col6.bed.sorted -b SPRINT_identified_all.res.col3.sorted -sorted

`Error: Sorted input specified, but the file wheat_col6.bed.sorted has the following out of order record
1A	10004888	10007706	TraesCS1A02G020200.1	0	-`

**Comment by iqraishtiaq** [comment]
> Can you try BEDOPS?
> 
> bedops --intersect a.bed b.bed > output.bed

ok after installing bedops i will try it

**Comment by iqraishtiaq** [comment]
> Can you try BEDOPS?
> 
> bedops --intersect a.bed b.bed > output.bed

`./bedops --intersect SPRINT_identified_all.res.col3.sorted wheat_col6.sorted.bed > result.bed`

` head result.bed`
> 1A	124189778	124189779
1A	124189787	124189788
1A	124189792	124189793
1A	124189797	124189798
1A	124787186	124787187
1A	124787192	124787193
1A	124787204	124787205
1A	124787218	124787219
1A	124787237	124787238
1A	225507600	225507601

I have used bedops intersect and i think it has given me the the required results but the gene name and strand information is not give which is present in wheat.bed file.
Sir kindly check my results and suggest me something more.

**Comment by jumphone** [comment]
bedmap --echo res.bed  gene.bed> mapped.bed

**Comment by iqraishtiaq** [comment]
Gene.bed ??????
Is it wheat.bed file ?

**Comment by jumphone** [comment]
yes

**Comment by jumphone** [comment]
wheat_col6.sorted.bed

**Comment by iqraishtiaq** [comment]
> `./bedmap --echo SPRINT_identified_all.res.col3.sorted wheat_col6.sorted.bed > mapped.bed`

> `$ head mapped.bed`

> 1A	11664892	11664893
1A	11664901	11664902
1A	11664961	11664962
1A	11665022	11665023
1A	11665066	11665067
1A	124189765	124189766
1A	124189778	124189779
1A	124189787	124189788
1A	124189792	124189793
1A	124189797	124189798
kindly check it

**Comment by jumphone** [comment]
Please follow the instruction (https://bedops.readthedocs.io/en/latest/content/reference/statistics/bedmap.html) to adjust the "echo" parameter.

**Comment by iqraishtiaq** [comment]
> Thanks, I have done with --echo-map.
`head SPRINT_identified_all.res.col3.sorted.results.mapped.bed `

> 1A	124189778	124189779|1A	124189772	124190156	TraesCS1A02G117000.1	0	-
1A	124189787	124189788|1A	124189772	124190156	TraesCS1A02G117000.1	0	-
1A	124189792	124189793|1A	124189772	124190156	TraesCS1A02G117000.1	0	-
1A	124189797	124189798|1A	124189772	124190156	TraesCS1A02G117000.1	0	-
1A	124787186	124787187|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	124787192	124787193|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	124787204	124787205|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	124787218	124787219|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	124787237	124787238|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	225507600	225507601|1A	225507557	225517408	TraesCS1A02G137900.1	0	-
 This is my final output but this file has not editing site which is predicted by Sprint. e.g AG ,TA
I coppied the location from here and then search in my SPRINT_identified_all.res file to see the editing site. but it's very difficult task.

> now i wanna do functional annotation of each gene. 

> i am searching my identified gene in T3/Wheat database. but doing it one by one is very difficult task. Is there any other solution to do this task ????

**Comment by jumphone** [comment]
1. You can write script to solve this problem.

2. Or, you can use the "match" function in EXCEL: https://exceljet.net/excel-functions/excel-match-function

**Comment by iqraishtiaq** [comment]
Thank You Sir...... I have done my work and achieved my required results.
 I wanna ask a question...

> I have a 16S DNA sequence of Cynobacteria. It is a conserved region in Cynobacteria by which we do identification of this bacteria. we have amplified just a specific sequence and then sequenced it. 
can i predict the editing site from that sequenced data by using SPRINT.?????

**Comment by jumphone** [comment]
The most important part of SPRINT is the clustering of duplet editing sites. 

You can try to apply SPRINT to identify editing on 16s rRNA.

But I’m not sure about that whether there is “duplet editing sites” on 16s rRNA.

You can change the clustering parameters based on the help manual of SPRINT.

https://github.com/jumphone/SPRINT/blob/master/SPRINT_manual.pdf

**Comment by iqraishtiaq** [comment]
my question is " SPRINT can be worked on DNA sequence ?? " ???????

**Comment by jumphone** [comment]
SPRINT is designed for "detecting" editing sites, not "predicting". 

If there are duplet DNA editing sites on DNA sequence, SPRINT can detect them.

**Comment by iqraishtiaq** [comment]
sir I have not NGS data of 16sRNA ..it is not in .fq format.

>  head forward.fa

>CGTCCGGTCTGCTTACCATGCAAGTCGAACGGTCTCTTCGGACATAGTGGCGGACGGGTGAGTAACGCG
TGAGAACCTGCCTTTAGGTTGGGGATAACCCCTGGAAACGGGGGCTAATACCGAATGTGTCTTAAGATG
AAAGGTTTATTGCCTGAAGATTGGCTCGCGTCTGATTAGCTAGTTGGAGTGGTAACAGCGCACCTAGGC
GACGATCTGTACTTGGTCTGAGAGGATGACCAGGCACACTGGGACTGAGACACGGTCCAGACTCCTACG
GGAGGCAGCAGTGGGGAATTTTCCGCAATGGGCGAAAGCCTGACGGAGCAATACCGCGTGGGGGAGGAC
GGCTTTTGGGTTGTAAACCTCTTTTGTTAGGGAAGAATCGATGACGGTACCTGATGAATCAGCCTCGGC
TAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCAAGCGTTATCCGGAATTATTGGGCGTAAAGC
GTCCGTAGGTGGTTTATCAAGTCTGCTGTCAAAGACTGCGGCTTAACTGTGTAAAGGCAGTGGAAACTG
ATAAGCTAGAGTGCGATAGGGGTAAAGGGAATTCCCAGTGTAGCGGTGAAATGCGTAGATATTGGGAAG
AACACCAGCGGCGAAAGCGCGCTACTGGGCCTGCACTGACACTGAGGGACGAAAGCTAGGGGAGCGAAA

>  head reverse.fa
>AACTCAGACTGCGTCGGCGTCTCCTCCGCGAACGGTAGAAGTAACGACTTCGGGCGTGACCCAGCTCCCGGGG
TGTGAGGGGGGTGTGTACAGGCCCGGGAACGGATTCCCGCCGTATGCTGACCGGCGATTCTAGCGATTCCGCC
TTCGCGCAGGCGAGTTGCAGCCTGCGATCTGAACTGAGCGCCGGTTTATGAGATTGGCTCGCCCTCGCTGGTT
GGCTGCTCTTTGTCCAAAGCATTGTAGTACGTGTGTCGCCCAAGGCGTATGGGGCATGCTGACTTGACGTCAT
CCCCACCTTCCTCCGGTTTGTCACCGGCAGTCTCTCTAGAGTGCCCATCTGAAAGGCGGGCAATAAAAGACGA
GGGTGGCCTTCGTGGGGGAACTTACCCCAACTTCCAAGAACCCAAGTGGACAACGCCATGGCACCACTGGTGT
TCCGGTTCCGAAAGGCCCCCTCTGTTTTCTCAGAGGTCCCAGAATTGTCAGGCTCGGTAAGGGTTCTTCCGGT
TGCTCCAATTAAACCCCCTTCTTCCACGGCTGGGGCGGGCCCCCGTCAATTCTTTTAATTTCAACACTTGCGT
GCCGAATCCCCCAGGGGAGAAACTTACGGGGTGGCTTCGGATACAGCTCGGGGTCGATACGTGCTACACCTAG
TTGTCATCGTTTACAGCTAGGACTACTGGGGGTATCTAATCCCTTTCGCTCCCCTAGCTTTCGTCCATCAGTG


can you tell me please what i can do on these sequences as a bioinformatics student. ???
SPRINT is helpful to detect editing site in this data ???? 
please guide me if you can

**Comment by jumphone** [comment]
You can use this sequence as a reference and then apply SPRINT to your NGS data.

If you don't have NGS data, SPRINT cannot help you.

**Comment by iqraishtiaq** [comment]
I wanna categorize alu RES, repetitive non-alu RES and non- repetitive RES. how i can do it? kindly help me 
Thank You

**Comment by jumphone** [comment]
Please see https://github.com/jumphone/SPRINT/issues/7

**Comment by iqraishtiaq** [comment]
He had files of alu and non alu etc
But my SPRINT have not generated these type of files

**Comment by iqraishtiaq** [comment]
He had files regular_alu.res, regular_nalurp.res, regular_nrp.res, regular_split.res, regular_overall.res. but i havn't these kinds of files in my SPRINT results. 
Thanks

**Comment by jumphone** [comment]
What kind of species did you analyzed? 

You can download the repeat annotation file from: https://sourceforge.net/projects/sprintpy/files/dbRES/.

Feng

**Comment by iqraishtiaq** [comment]
i am working on wheat

**Comment by iqraishtiaq** [comment]
I am working on wheat genome. How i can make a repeat annotation file of wheat I have check this link
https://sourceforge.net/projects/sprintpy/files/dbRES/

but could not find the for wheat. please tell me how can i get this repeat file

**Comment by jumphone** [comment]
I'm not familiar with the repeat regions of plant. 

Maybe you can use SPRINT without using repreat annotation file.

Feng
