### ISSUE TITLE
How to annotate the final.res to gene or symbol?  I just want to focus on specific gene.

### ISSUE THREAD

**Issue by ShawnXPan** [jumphone/SPRINT#2]

**Comment by jumphone** [comment]
Please remove the header of the RES file generated by SPRINT, and then use BEDTOOLs to annotate the RES file with gene annotation file (in BED format). e.g. “bedtools intersect” or “bedtools coverage”

**Comment by iqraishtiaq** [comment]
I wanted to annotate the final three .res files to gene or symbol. 
firstly i removed header of .res files
`head SPRINT_identified_all.res`

> 1A	135397	135398	CT	2	+	2:75
1A	135420	135421	CT	1	+	1:181
1A	135429	135430	CT	1	+	1:193
1A	135446	135447	CT	1	+	2:208
1A	135450	135451	CT	1	+	1:206
1A	11664892	11664893	GA	1	+	7:31
1A	11664901	11664902	GA	1	+	16:42
1A	11664961	11664962	GA	3	+	35:94
1A	11665022	11665023	GA	5	+	34:107
1A	11665066	11665067	GA	4	+	16:87

I have converted gtf file into bed file and after that used this command 
`bedtools intersect -a SPRINT_identified_all.res -b wheat.bed -u` 
and got this error
`ERROR: Received illegal bin number 37458 from getBin call.`
`ERROR: Unable to add record to tree.`
