### ISSUE TITLE
Is the trimming first 6 bases step included in your pipeline?

### ISSUE THREAD

**Issue by YichaoOU** [jumphone/SPRINT#20]
Hi,

In your paper, you have performed: "Before mapping, the first 6 bases of each read were trimmed to avoid mapping errors caused by random-hexamer primers."

Is this process included in SPRINT main?

Thanks,
Yichao

**Comment by jumphone** [comment]
You can use the option "-c N" to trim first N bases (default is 0)

**Comment by YichaoOU** [comment]
Cool!
