### ISSUE TITLE
Why the rate of A-to-G deteced by SPRINT is very low ?

### ISSUE THREAD

**Issue by qiuyixmm** [jumphone/SPRINT#21]
Hello,
     I downloaded mouse RNA-Seq data from NCBI as test data to run SPRINT. The accession code of my downloaded data is SRR1920270.
    Firstly, I run SPRINT without adding repeats bed file after trim the downloaded data using Trimmomatic-0.32. There is my command below:

~/bin/SPRINT-0.1.8/bin/sprint prepare \
 -t  ~/test/genome_file/Mus_musculus.GRCm38.96.gtf \
 ~/test/genome_file/Mus_musculus.GRCm38.96.genome.fa \
~/bin/SPRINT-0.1.8/samtools_and_bwa/bwa

 ~/bin/SPRINT-0.1.8/bin/sprint main -c 6 -p 10 \
 -1 ~/test/SRR1920270-1/SRR1920270_R1.clean.fastq \
 -2 ~/test/SRR1920270-1/SRR1920270_R2.clean.fastq \
~/test/genome_file/Mus_musculus.GRCm38.96.genome.fa \
~/test/SRR1920270 \
~/bin/SPRINT-0.1.8/samtools_and_bwa/bwa \
~/bin/SPRINT-0.1.8/samtools_and_bwa/samtools

> cut -f 4 SPRINT_identified_regular.res | sort | uniq -c
     53   AC
   1478 AG
     20   AT
     33   CA
     41   CG
   1354  CT
   1206 GA
     36   GC
     31   GT
     21   TA
   1471 TC
     41   TG
      1 Type

   The rate of  A-to-G is much less than 90% which is confict with the common conclusion in mouse. Additonally, the rates of C-to-T and G-to-A were comparable to the rate of A-to-G. I guess that perhaps SNVs were not removed in low complexity regions and simple repeats without providing repeat annotation file.  And then I ran SPRINT again with repeat annotation file downloaded from UCSC. Here is my second command:

 ~/bin/SPRINT-0.1.8/bin/sprint main -c 6 -p 10 \
-rp ~/test/genome_file/mm10.repeats.bed \
 -1 ~/test/SRR1920270-1/SRR1920270_R1.clean.fastq \
 -2 ~/test/SRR1920270-1/SRR1920270_R2.clean.fastq \
~/test/genome_file/Mus_musculus.GRCm38.96.genome.fa \
~/test/SRR1920270 \
~/bin/SPRINT-0.1.8/samtools_and_bwa/bwa \
~/bin/SPRINT-0.1.8/samtools_and_bwa/samtools

> cut -f 4 SPRINT_identified_regular.res | sort | uniq -c
     15 AC
   1117 AG
     25 AT
     28 CA
     20 CG
    597 CT
    546 GA
     21 GC
     30 GT
     21 TA
   1039 TC
     30 TG
      1 Type

The rate of  A-to-G was increased but still much less than 90%. And the rates of C-to-T and G-to-A were also very high. I don't know where is the problem. Could you give me some help? Thanks!
    
Best regard,

**Comment by jumphone** [comment]
1. Please use repeat annotation file (you can use mm10 as reference).

Do you see “chr” ahead the name of each chromosome in your reference?

2. C-to-U rate can be high in some mouse tissues (please check our manuscript).

**Comment by qiuyixmm** [comment]
Hello,
     Thanks for the reply. 
      I used repeat annotation file to run  SPRINT in my second tries (see obove).  The repeat annotation file downloaded from UCSC was processed using rp2bed.py firstly and then the generated bed file (mm10.repeats.bed) was used as input for SPRINT.  
     In my downloaded mouse reference genome file, there are no "chr" ahead the name of each chromosome. So I also removed "chr" in mm10.repeats.bed file before running SPRINT. But The rate of A-to-G was increased but still much less than 90%.  BTW,  SRR1920270 is RNA-Seq data of mouse ( CAST-EIJ strain) brain tissue.

**Comment by jumphone** [comment]
Unlike primate, mouse can have high C-to-U rate.

However, it may caused by the condition or sequencing protocol of this sample.
 
Maybe you can try another dataset.
