### ISSUE TITLE
Generated binary files not working

### ISSUE THREAD

**Issue by AliSajid** [jumphone/SPRINT#22]
Hi,

I am trying to use the binaries but they report the following error:

```
$ sprint
zsh: exec format error: sprint
```

Can you please help?

**Comment by jumphone** [comment]
Hi, 

What's your operating system?

**Comment by AliSajid** [comment]
Hi,

It’s a MacOS Mojave 10.14.6

**Comment by jumphone** [comment]
The binary file has only been tested in Linux system (Centos and Ubuntu).

Can you try the python2.7 version ?

**Comment by AliSajid** [comment]
Yes, the python 2.7 version works. I was just hoping to use a portable binary.

Thank you for the help.

Are there any plans to port this to Python 3?

**Comment by jumphone** [comment]
Yes, we are developing a new version of SPRINT.

Actually, you can compile the python version into binary file by yourself.

Please see: https://github.com/jumphone/SPRINT/blob/master/pyinstaller.sh

**Comment by AliSajid** [comment]
Perfect. Thanks.
