### ISSUE TITLE
zz2sam.py hard-codes strandedness

### ISSUE THREAD

**Issue by MaxHills** [jumphone/SPRINT#23]
All sam files output by zz2sam.py ignore the sam_flag indicated in the all_combined.zz file and hard-code sam_flag 0 into the sam file. This program also outputs more reads than are present in the original all_combined.zz file. Also, many reads have an asterisk in multiple fields in the all_combined.zz file. These ```*``` containing reads contain no information about RNA-editing and yet are presumed to be RNA-edited reads based on a straight-forward reading of the SPRINT manual.

**Comment by jumphone** [comment]
1. You can write your own script to keep strand information

2. If there is a gap in a read, zz2sam will separate this read into 2 reads.

3. Not all reads in “all_combined.zz” are edited reads.

**Comment by MaxHills** [comment]
What is the criteria for a read being included in all_combined.zz? I.e., what do these reads represent?

**Comment by jumphone** [comment]
All reads. It includes all mapped and re-mapped reads. 

In that file, you can see the variants of each read.

You can get edited reads by matching edited sites to variants in each read.

**Comment by MaxHills** [comment]
If "all_combined.zz" represents all mapped and re-mapped reads, then approximately 25% of my library reads are being mapped. 
I am using mouse mm10 single-end data with read length of ~100bp. When using STAR aligner on the same data, approximately 80% of my reads are being mapped. 
I am using the following command, expecting the first 12 nucleotides to contain random primers:

sprint main \
-1 $data/ACTTGA/ACTTGA.fq \
-rp mm10/mm10.repeat.txt \
-ss 0 \
-c 12 \
-p 4 \
mm10/mm10.ucsc.fa \
$data/ACTTGA/SPRINT_out \
~/.local/bin/bwa-0.7.12/bwa \
~/.local/bin/samtools-1.2/samtools

Is there any reason I should expect such low mapping rates?

**Comment by jumphone** [comment]
Because SPRINT uses BWA. In SPRINT, we follow the design of Ramaswami et al. to use BWA. Mapping of BWA follows more stringent rule than STAR. Actually, when dealing with SNP calling using DNA-seq  data, BWA is still one of the best choices ( see GATK).
