### ISSUE TITLE
how to calculate the no. of editing sites present in 3' UTRs and CDS and 5'TRS???

### ISSUE THREAD

**Issue by iqraishtiaq** [jumphone/SPRINT#24]
I have mapped identified RES with the referance genome . now i wanna find and count the no. of editing site present in UTR or CDS region ??? 
` head SPRINT_identified_all.res.col3.sorted.results.mapped.bed

> `1A	124189778	124189779|1A	124189772	124190156	TraesCS1A02G117000.1	0	-
1A	124189787	124189788|1A	124189772	124190156	TraesCS1A02G117000.1	0	-
1A	124189792	124189793|1A	124189772	124190156	TraesCS1A02G117000.1	0	-
1A	124189797	124189798|1A	124189772	124190156	TraesCS1A02G117000.1	0	-
1A	124787186	124787187|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	124787192	124787193|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	124787204	124787205|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	124787218	124787219|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	124787237	124787238|1A	124786601	124787399	TraesCS1A02G117400.1	0	-
1A	225507600	225507601|1A	225507557	225517408	TraesCS1A02G137900.1	0	-

**Comment by jumphone** [comment]
You can simply download the UTR annotation from UCSC table browser.

https://genome.ucsc.edu/cgi-bin/hgTables

Please set "output format:" to "BED", and then click "get output". In the pop-up window, you can select "UTR" regions.

Best,
Feng

**Comment by iqraishtiaq** [comment]
I am working on wheat genome ....there is no option to download UTRs for wheat genome. Kindly tell me any other way if you know .....Thanks

**Comment by iqraishtiaq** [comment]
I am working on wheat genome ....there is no option to download UTRs for wheat genome. Kindly tell me any other way if you know .....Thanks

**Comment by jumphone** [comment]
I've nerver annotated UTR of plant genome. 

Maybe you can check the following website: https://www.researchgate.net/post/How_can_find_out_the_UTR_of_the_gene.

Or, you may manually use the start flanking region (e.g. 2000bp around start site) and end flanking region (e.g. 2000bp around end site) as UTR, and clarify your strategy in the Method section of your paper.

Best,
Feng
