### ISSUE TITLE
Effect of editing sites on the condon changes 

### ISSUE THREAD

**Issue by fatimarasool** [jumphone/SPRINT#25]
Hi,
 I have detected the RNA editing sites by using the SPRINT  tool. i have the result file in .RES format as the SPRINT generate it. i have also find the the coding gene in which these RNA editing sites are present.  now i want to know about effect of these RNA editing sites on codon changes. kindly tell me how i can i find it ? i want to this type of information of my data as following 

**`acA/acG          glysine/serine`**
The file format is as following  after finding the genes in which RNA editing sites are present.

`1A	113251747	113251748|1A	113251083	113252461	gene1	0	-

1A	113251757	113251758|1A	113251083	113252461	gene1	0	-

1A	113251774	113251775|1A	113251083	113252461	gene1	0	-

1A	113251797	113251798|1A	113251083	113252461	gene1	0	-

`

**Comment by jumphone** [comment]
Hi,

You can try VEP ( https://m.ensembl.org/info/docs/tools/vep/index.html )
or ANNOVAR ( https://doc-openbio.readthedocs.io/projects/annovar/en/latest/ ).

Best,
Feng

**Comment by fatimarasool** [comment]
Hi Feng
                  Thank you so much for reply. you help me a lot in my
project of RNA editing site detection by SPRINT tool. now i am stuck in
annotation of these editing.
 The VEP tool take the VCF file format. while i have RES file format as you
know output of the SPRINT. while the ANNOVAR is for only the animals. i am
working on the wheat transcriptome.
The VEP tool not take the input file of sprint output file.

**Comment by jumphone** [comment]
You can follow "https://github.com/jumphone/SPRINT/blob/master/utilities/rp2bed.py" to write your own script. (you need to modify this python script)
