### ISSUE TITLE
SPRINT installation Error

### ISSUE THREAD

**Issue by iqraishtiaq** [jumphone/SPRINT#26]
By using command `pip install sprint` I am facing error as shown below.
It is installed successfully but not working. Don't know why? working on Ubuntu 20.04 latest version.

> iqra@workstation:~$ pip install sprint
> Collecting sprint
>   Downloading sprint-0.1.7.tar.gz (17 kB)
> Building wheels for collected packages: sprint
>   Building wheel for sprint (setup.py) ... done
>   Created wheel for sprint: filename=sprint-0.1.7-py2.py3-none-any.whl size=32230 sha256=04993b25bed388bd35eb7f09161e112f8182f760fd4c71518b5daaaab2cdf6ff
>   Stored in directory: /home/iqra/.cache/pip/wheels/ee/80/71/0e23721d6b3f2383975a997f8f74c350600ce2dd6cb720b50e
> Successfully built sprint
> Installing collected packages: sprint
>   WARNING: The script sprint is installed in '/home/iqra/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> Successfully installed sprint-0.1.7
> iqra@workstation:~$ sprint
> 
> Command 'sprint' not found, did you mean:
> 
>   command 'qprint' from deb qprint (1.1.dfsg.2-2build1)
>   command 'spring' from deb ruby-spring (2.1.0-1)
>   command 'spring' from deb spring (104.0+dfsg-4ubuntu7)
>   command 'print' from deb mime-support (3.64ubuntu1)
>   command 'lprint' from deb lprint (1.0-1)
>   command 'splint' from deb splint (1:3.1.2+dfsg-1build1)
> 
> Try: sudo apt install <deb name>

**Comment by jumphone** [comment]
1. Please directly download and use the executable binary file "sprint": https://github.com/jumphone/SPRINT/tree/master/bin
2. Please use “chmod” to change the permission:  "chmod 777 sprint"
Best,
Feng

**Comment by iqraishtiaq** [comment]
Thank you soooo much Sir. Issue is resolved.
can i use sam tools 1.12 version 
actually in samtools-1.2 during execution of `make` command I have following error.

> gcc -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=1 -I. -Ihtslib-1.2.1 -c -o 
> bam_tview_curses.o bam_tview_curses.c
> bam_tview_curses.c:30:10: fatal error: curses.h: No such file or directory
>  30 | #include <curses.h>
> |          ^~~~~~~~~~

**Comment by iqraishtiaq** [comment]
Thank you soooo much Sir. Its working perfect.
Please tell me after running sprint prepare commands how many files will be generated?
Actually I obtained 35 files and i am confused which one should be used for further processing in `sprint main` command

**Comment by jumphone** [comment]
1. You can download executable binary file "samtools" from : https://github.com/jumphone/SPRINT/tree/master/samtools_and_bwa
2. After finishing "sprint prepare", you can directly use "sprint main" without considering about those generated files. (the input .fasta file of "sprint main" is still the original fasta (e.g. hg19.fa, mm9.fa, etc.))

**Comment by iqraishtiaq** [comment]
By running following command getting these errors. My all files generated by sprint prepare, refernce genome, sam and bam tools are present in Downloads folder. 
`./sprint main -1 R1.fq -2 R2.fq buffalo_reference_genome.fa /home/iqra/Downloads ./samtools-1.2/samtools ./bwa-0.7.12/bwa`

> preprocessing...

> mapping...
> [main] unrecognized command 'aln'
> [main] unrecognized command 'aln'
> [main] unrecognized command 'samse'
> [main] unrecognized command 'samse'
> [main] unrecognized command 'view'
> [main] unrecognized command 'view'
> [main] unrecognized command 'sort'
> [main] unrecognized command 'sort'
> [main] unrecognized command 'merge'
> [main] unrecognized command 'view'
> cp: cannot stat '/home/iqra/Downloads//tmp//genome/./all.sam': No such file or directory
> [main] unrecognized command 'view'
> [main] unrecognized command 'aln'
> [main] unrecognized command 'samse'
> [main] unrecognized command 'view'
> [main] unrecognized command 'sort'
> [main] unrecognized command 'view'
> cp: cannot stat '/home/iqra/Downloads//tmp//transcript/./all.sam': No such file or directory
> [main] unrecognized command 'view'
> [main] unrecognized command 'aln'
> [main] unrecognized command 'samse'
> [main] unrecognized command 'view'
> [main] unrecognized command 'sort'
> [main] unrecognized command 'view'
> cp: cannot stat '/home/iqra/Downloads//tmp//genome_mskAG/./all.sam': No such file or directory
> [main] unrecognized command 'view'
> [main] unrecognized command 'aln'
> [main] unrecognized command 'samse'
> [main] unrecognized command 'view'
> [main] unrecognized command 'sort'
> [main] unrecognized command 'view'
> cp: cannot stat '/home/iqra/Downloads//tmp//genome_mskTC/./all.sam': No such file or directory
> [main] unrecognized command 'view'
> [main] unrecognized command 'aln'
> [main] unrecognized command 'samse'
> [main] unrecognized command 'view'
> [main] unrecognized command 'sort'
> [main] unrecognized command 'view'
> cp: cannot stat '/home/iqra/Downloads//tmp//transcript_mskAG/./all.sam': No such file or directory
> [main] unrecognized command 'aln'
> [main] unrecognized command 'samse'
> [main] unrecognized command 'view'
> [main] unrecognized command 'sort'
> [main] unrecognized command 'view'
> cp: cannot stat '/home/iqra/Downloads//tmp//transcript_mskTC/./all.sam': No such file or directory
> Traceback (most recent call last):
>   File "run.py", line 7, in <module>
>   File "sprint/pipeline.py", line 42, in pipeline
>   File "sprint/sprint_main.py", line 458, in main
>   File "sprint/tools_sam/recover_sam.py", line 39, in recover_sam
> IOError: [Errno 2] No such file or directory: '/home/iqra/Downloads//tmp/transcript_mskAG_all.sam'
> Failed to execute script run
>

**Comment by jumphone** [comment]
It should be "./sprint main -1 R1.fq -2 R2.fq buffalo_reference_genome.fa /home/iqra/Downloads ./bwa-0.7.12/bwa  ./samtools-1.2/samtools".

"./bwa-0.7.12/bwa" should be in front of "./samtools-1.2/samtools"

**Comment by iqraishtiaq** [comment]
please tell me what should be the specifications of system/PC/laptop to run Sprint?
My laptop has Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz 2201 Mhz, 4 core(s), 8 Logical... processor.
RAM is 4 GB. Available virtual memory is 10.6 GB.
I am working on buffalo genome. Forward and reverse reads file size is 6GB each and reference genome file is 3GB in size.

**Comment by jumphone** [comment]
> please tell me what should be the specifications of system/PC/laptop to run Sprint?
> My laptop has Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz 2201 Mhz, 4 core(s), 8 Logical... processor.
> RAM is 4 GB. Available virtual memory is 10.6 GB.
> I am working on buffalo genome. Forward and reverse reads file size is 6GB each and reference genome file is 3GB in size.

1. We've tested SPRINT on Centos7 and Ubuntu.

2. You may need more memory. For a 6GB unzipped FASTQ file (single end), SPRINT, SAMTOOLS, and BWA may need around 6GB +3GB (reference genome) memory to process the data (rough estimation).
