### ISSUE TITLE
Differential RNA Editing

### ISSUE THREAD

**Issue by kokyriakidis** [jumphone/SPRINT#27]
Hi!

Do you have a script to perform differential editing analysis (case-control samples) using the output tables of SPRINT?

**Comment by jumphone** [comment]
Currently, we didn't have a script for the differential analysis. 
It really depends on the research goal. For example, if you set individual gene as the research element, you may need to combine all editing sites within one gene to do the differential analysis.

**Comment by kokyriakidis** [comment]
Generally how do you annotate the tables SPRINT produces? Is there a way to convert the into vcf to annotate properly with all available tools? (vep etc)

**Comment by jumphone** [comment]
You can write a simple script to change the output of SPRINT (BED format) to "Ensembl default" format, and then run VEP.

https://grch37.ensembl.org/Tools/VEP

1 818046 818046 T/C 1
2 265023 265023 C/A 1
3 361464 361464 A/- 1
