### ISSUE TITLE
Compared the RESs called by SPRINT and RESs from RADAR database

### ISSUE THREAD

**Issue by mt831** [jumphone/SPRINT#3]
Hi. I compared the RESs called by SPRINT and RESs from RADAR database, and find only 18% RESs are overlaped. That means many RESs called by SPRINT are not found in this database. Does this mean that the sites I found are inaccurate? Thank you.

**Comment by jumphone** [comment]
No. You should check whether RADAR identify RESs using the same RNA-seq data. Every sample may have distinct RESs.
