### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by xikanfeng2** [jumphone/SPRINT#31]
error happens with import sprint from python console
<img width="554" alt="截屏2021-12-16 下午4 43 47" src="https://user-images.githubusercontent.com/8011600/146337804-22e524f5-8ed5-40cd-b292-141e8da6d312.png">
.
It should be from .tools_fq import *?

**Comment by jumphone** [comment]
please directly use the binary file of SPRINT: https://github.com/jumphone/SPRINT/tree/master/bin

**Comment by xikanfeng2** [comment]
We want to use the sprint.annotate and sprint.seperate to split alu, non-alu, and non-repetitive regions.  Are these commands can be found in binary file?

**Comment by jumphone** [comment]
You can simply copy the code to your file. Such as "annotate.py" in  https://github.com/jumphone/SPRINT/blob/master/sprint/tools_bed/annotate.py. By the way, maybe you can try bedtools, it has similar function.
