### ISSUE TITLE
reverse strandedness -ss 1 or -ss 2

### ISSUE THREAD

**Issue by ojziff** [jumphone/SPRINT#32]
Hi @jumphone 

Great tool!

I have reverse stranded 100bp paired end RNAseq and I specified `-ss 1` assuming reverse == sense strandedness. However, in the output I see that the vast majority of AG editing types are on the - strand, and TC on the + strand which is opposite of what i expected.

I ran sprint from fastq on trimmed unzipped fastqs with command
```
sprint main -rp hg38_repeat.txt -ss 1 -p 12 -1 sample_1_R1.fq -2 sample_1_R2.fq GRCh38.dna.primary_assembly.fa $OUT/sample_1 bwa samtools
```
Can you confirm that i should specify `-ss 1` for reverse stranded RNAseq?

Thanks very much!
Oliver

**Comment by jumphone** [comment]
Hi, please check the manual of SPRINT ( typically, -ss should be 0 ):

-­‐ss INT
# when input is strand-­‐specific sequencing data, please clarify the direction of read1. [0 for antisense; 1 for sense] (default is 0)

**Comment by ojziff** [comment]
Thanks @jumphone for quick response.

Input is reverse stranded RNAseq made with TruSeq Stranded mRNA kit. Reading https://www.illumina.com/products/by-type/sequencing-kits/library-prep-kits/truseq-stranded-mrna.html  I think it is antisense rather than sense. Please could you confirm should -ss be 0 for TruSeq Stranded mRNA?

**Comment by jumphone** [comment]
Hi, 

I saw a sentence in the manual of TruSeq Stranded mRNA kit: "Strand specificity is achieved by replacing dTTP with dUTP in the SMM (Second Strand Marking Mix), followed by second strand cDNA synthesis using DNA Polymerase I and RNase H." 

In my experience, for data using "dUTP" step, "-ss" should be "0".  

Thanks for using SPRINT.

**Comment by ojziff** [comment]
Very helpful, thank you!
