### ISSUE TITLE
No results in final result files

### ISSUE THREAD

**Issue by Sunmile** [jumphone/SPRINT#33]
Hi Feng,
Thanks for developing the SPRINT.
I'm trying to find the possible RNA editing sites which may change the protein sequence with the help of SPRINT.  Since I have done the RNA mapping with the STAR and gotten the sorted bam files.  I use the 'sprint_from_bam.py' directly to save time. 
The run process is well-going without any error information. However, the final result file contains no RNA editing information.  
The command is as follows:
```
python /hwangxy/software/SPRINT/sprint_from_bam.py \
-rp /hwangxy/RNA_edit/data/dbrep/hg38_repeat.txt \
/RNAseq/all_bam/P001_Aligned.sortedByCoord.out.bam \
/hwangxy/reference/TCGA_GRCh38_bwa_ref/GRCh38.d1.vd1.fa \
/hwangxy/RNA_edit/result/Sprint/test_out/  \
/hwangxy/anaconda3/envs/py27/bin/samtools
```
The command output is like this:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/28746628/209082105-86639288-3075-4db2-95dd-c27f03937196.png">
And the final results files:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/28746628/209082354-4d1619f6-4f05-4675-b0a6-40852e8da870.png">
Other res_files in tmp directory:
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/28746628/209082520-9190530b-bbca-4e3e-9343-84773b73ef31.png">

The python version is 2.7.18 and samtools version is 1.2. I also can ensure that there are several RNA edit sites in my test bam file which I can see in the IGV window.

Another thing I'm not sure about is that the command was run in an HPC with 20 CPU cores and 32G Memory. But I ran several times which average time consumption is about 3.5 hours (without RNA mapping). Is this normal?

I would appreciate it if you can provide any help.
Many thanks,
Sunmile

**Comment by jumphone** [comment]
Hi, 
1. please use "sprint prepare" to build the index of reference genome before using sprint.
2. please directly use "sprint main" (because I'm not sure wether the BAM file of th latest STAR can be used by the "sprint_from_bam").
Best,
Feng

**Comment by Sunmile** [comment]
Hi Feng,

Thanks for the answer, I'll try it.

Regards,
Sunmile
