### ISSUE TITLE
What ref .fa file to use for sprint main after prepare?

### ISSUE THREAD

**Issue by haydenshinn** [jumphone/SPRINT#35]
I was successfully able to run sprint prepare but there are a lot of different output files including multiple fasta files such as **.fa.mskAG.fa, .fa.mskTC.fa, .fa.trans.fa, .fa.trans.fa.mskAG.fa, and .fa.trans.fa.mskTC.fa**. I understand the purpose of sprint prepare is to mask the reference genome and build a mapping index but when running sprint main _are we supposed to use the same original reference fasta or use one of the reference fastas outputted from the prepare_? I am confused as there is not much of an explanation as to what is going on in this step and how its output will be applied to/used in the main script. Thanks!

**Comment by jumphone** [comment]
Please use the original fasta, and sprint will use those ".fa" automatically.
