### ISSUE TITLE
Some editing sites can not be identified but it has editing reads when viewing with IGV. 

### ISSUE THREAD

**Issue by JieWu2012** [jumphone/SPRINT#37]
Hi, 

I used Sprint to identify editing sites. Same script to two samples. The IGV shows this editing site exist for both samples. But in the Sprint results, I can only find this site in the first sample, but not in the second sample. Any idea what is the problem? 
![Screenshot 2024-01-30 at 5 38 15 PM](https://github.com/jumphone/SPRINT/assets/4727669/d7e433d5-382b-4b6b-89d5-4c112597cfbe)

**Comment by jumphone** [comment]
Hi, SPRINT has multiple types of thresholds for removing false positives, which might cause this issue. 

One possible way to solve this problem:

Merge the RES lists of multiple samples, and then re-calculate the AD and DP.

For AD:
1. convert sam to zz (https://github.com/jumphone/SPRINT/blob/master/utilities/sam2zz.py)
2. calculate AD (https://github.com/jumphone/SPRINT/blob/master/utilities/getAlt.py)

For DP:
Use bedtools to calculate the coverage of each RES

Best,
Feng

**Comment by JieWu2012** [comment]
Hi Feng, 

Thank you very much for the reply. It sounds like a good idea to re-calculate the AD and DP. Concerning the getAlt.py, is there any manual to explain what is the input and output? Besides, in the output of sprint from previous running, there is already a result file called "all_combined.zz". Do I still need to convert sam to zz?

**Comment by jumphone** [comment]
1. The output of getAlt.py is: CHR+'\t'+LOC+'\t'+TYP+'\t'+AD+'\n' 
2.  You can directly use the all_combined.zz.
