### ISSUE TITLE
Samtools Problem_ symbol lookup error: /lib64/libncurses.so.5: undefined symbol: _nc_tiparm

### ISSUE THREAD

**Issue by korinakg** [jumphone/SPRINT#38]
Hello, I am trying to run sprint main, but at some point I get the error below: 

home/k/korinagk/.conda/envs/runSPRINT/bin/samtools: symbol lookup error: /lib64/libncurses.so.5: undefined symbol: _nc_tiparm
/home/k/korinagk/.conda/envs/runSPRINT/bin/samtools: symbol lookup error: /lib64/libncurses.so.5: undefined symbol: _nc_tiparm
/home/k/korinagk/.conda/envs/runSPRINT/bin/samtools: symbol lookup error: /lib64/libncurses.so.5: undefined symbol: _nc_tiparm
cp: /tmp/_MEIwqC3Sh/libselinux.so.1: no version information available (required by cp)
cp: cannot stat '/mnt/hcctcga_a/groups/hcctcga/lab_members/korinagk/RVHF/sprint/results/47_DCM_P3_S47//tmp//genome_mskTC/./all.sam': No such file or directory
/home/k/korinagk/.conda/envs/runSPRINT/bin/samtools: symbol lookup error: /lib64/libncurses.so.5: undefined symbol: _nc_tiparm

I tried update the samtools version and also ncurses version in my conda enviroment but it didn't work. 

Can you please help me? 

Thank you in advance

**Comment by jumphone** [comment]
Please search more details about running SAMTOOLS == 1.2 or installing SAMTOOLS == 1.2 from source code.

**Comment by korinakg** [comment]
I indeed use a conda enviroment with SAMTOOLS == 1.2, PYTHON == 2.7 and BWA == 0.7.12 as recommended by your guidelines, but I still face the same problem. 
Below I am giving the list of all packages (and their versions) included in the conda environment I am using to run sprint_main:

_libgcc_mutex (0.1)  
_openmp_mutex (5.1)  
bwa (0.7.12)
ca-certificates (2024.7.2)  
certifi (2020.6.20)  
libffi (3.4.4)  
libgcc-ng (11.2.0) 
libgomp (11.2.0)  
libstdcxx-ng (11.2.0)
ncurses (6.4) 
openssl (1.1.1w) 
pip (19.3.1)  
python (2.7.18)  
readline (8.2)  
samtools (1.2)
setuptools (44.0.0) 
sqlite (3.45.3)  
tk (8.6.14)  
wheel (0.37.1)  
zlib (1.2.13)

**Comment by jumphone** [comment]
Maybe, you can try to install it from the source code:

1.2 but not 1.20

https://github.com/samtools/samtools/releases?page=3

https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2

https://github.com/samtools/samtools/archive/refs/tags/1.2.zip

**Comment by korinakg** [comment]
Dear jumphone,

I just realize that my servers in the cluster I am working on currently, have changed from unix to linux. Is it possible that this is the reason I am getting that error? 

Thank you in advance for your answer and help.
