### ISSUE TITLE
How to prepare repeat files？

### ISSUE THREAD

**Issue by LIUXING-bio** [jumphone/SPRINT#39]
How can I obtain the repeat files of any other non-model species?  For example, if I have obtained the result file through Repeatmasker, how can I change it to the input data of the software?  Are there any examples?

**Comment by jumphone** [comment]
Hi,
1. You can download repeat file ("dbrep.zip") from https://sourceforge.net/projects/sprintpy/files/dbRES/  
2. You can use "rp2bed.py" to change it (https://github.com/jumphone/SPRINT/tree/master/utilities)
3. You can directly run sprint without repeat annotation (may miss some RESs)
Best,
Feng
