### ISSUE TITLE
Some questions about your lab and project.

### ISSUE THREAD

**Issue by neargle** [jumphone/SPRINT#4]
您好，我是一名对生物统计和生命科学比较感兴趣的信息技术从业者，目前从事信息安全和数据分析相关的领域研究，一直关注着您的项目和实验室的动态。

可是实验室的官网 http://tianlab.cn/ 以及子域从四月中旬开始就无法访问，能否留给我一个邮箱或者社交网络的id，以便联系交流？

Thx.

**Comment by jumphone** [comment]
Contact information of Dr. Tian: 

http://life.fudan.edu.cn/Data/View/1408

Best,

Feng
