### ISSUE TITLE
Issue with ASCII value

### ISSUE THREAD

**Issue by Stephen1202-Wang** [jumphone/SPRINT#40]
Hi,
Thanks for developing this tool! I ran into an issue when using SPRINT, which I traced to the following lines in the code:
```
if ord(i)>76:
    fo.write('89')
    did=1
    break
if ord(i)<60:
    fo.write('58')
    did=1
    break
```
I'm working with a dataset where all values are 'F', which has an ASCII code of 70. This value doesn’t meet any of the specified conditions. As a result, it would generate an empty file which stops downstream analysis. 

Do you have any recommendations on how to handle this scenario, or thoughts on adjusting these criteria to accommodate values like 'F'?

Thanks so much for your time and assistance!

**Comment by jumphone** [comment]
You can add a "baseq.cutoff" file under the folder named "tmp". And then write "58" in it. 

The baseline of your fastq quality score might be "33". Then the cutoff is "33+25=58".

**Comment by Stephen1202-Wang** [comment]
Hi @jumphone,

Thanks for you suggestion! The issue has been successfully resolved.
