### ISSUE TITLE
How to accelerate the  process

### ISSUE THREAD

**Issue by mt831** [jumphone/SPRINT#5]
Hi,

I used the command below :
sprint main   -rp   ~/my_refdata/hg19_sprint/hg19_repeat.txt   -c   6   -p   12   -1  normal_11_1.fq   -2  normal_11_2.fq  ~/my_refdata/hg19_sprint/hg19.fa normal_11_output bwa   samtools
but it takes a long time to get the results. About two days, maybe. Are there some ways to accelerate the  process ? 
By the way, the size of normal_11_1.fq is 23G.

Thanks.

**Comment by jumphone** [comment]
Hi,

1. You can use more CPUs to accelerate the alignment process.

2. You can accelerate the RES detection process by directly using SPRINT Python package. If you are familiar with Python, please install the SPRINT package in Python 2.7 ("pip install sprint").
After that, you can separate the FASTQ file into several small files, and then follow the python code in (https://github.com/jumphone/SPRINT/blob/master/sprint/sprint_main.py) to deal with these files at the same time. Finally you can combine the SNVs identified from each file, and then conduct the clustering.

Best,

Feng

**Comment by mt831** [comment]
Thank you. I'll try.

**Comment by iqraishtiaq** [comment]
Hi Feng 
please tell me what should be the specifications of system/PC/laptop to run Sprint?
My laptop has `Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz 2201 Mhz, 4 core(s), 8 Logical...` processor.
RAM is 4 GB. Available virtual memory is 10.6 GB.
I am working on buffalo genome. Forward and reverse reads file size is 6GB each and reference genome file is 3GB in size.
