### ISSUE TITLE
Count total edited reads from all_combined.zz

### ISSUE THREAD

**Issue by mt831** [jumphone/SPRINT#6]
Hi, 
    I noticed that edited reads can be extracted from "tmp/all_combined.zz". So is it possible for me  to count total edited reads from all_combined.zz ? Each line in all_combined.zz file means one edited read?

Thank you.

**Comment by jumphone** [comment]
“all_combined.zz” is a file having all mapped and re-mapped reads (not only edited reads). 

If you are familiar with BAM file, you can transfer ZZ to BAM by following the instruction in the README file of SPRINT  (1. Edited reads can be extracted from "tmp/all_combined.zz”.)

Or you can extract edited reads from ZZ file. The format of ZZ file is also provided in: 1. Edited reads can be extracted from "tmp/all_combined.zz”.

Best,

Feng

**Comment by mt831** [comment]
As you said “all_combined.zz” was a file having all mapped and re-mapped reads, so can I count total mapped reads using the all_combined.zz file ? Could I count the total rows of the file to get all mapped reads? Is that right? Or I still need to get the bam file.

**Comment by jumphone** [comment]
Yes, you can do that.

**Comment by mt831** [comment]
Thank you for your quick reply. I'll try.
