### ISSUE TITLE
How can I count the RNA editing sites in Alu, non-Alu and non-repeat region?

### ISSUE THREAD

**Issue by mt831** [jumphone/SPRINT#7]
Hi,
I found there are files: regular_alu.res, regular_nalurp.res, regular_nrp.res, regular_split.res, regular_overall.res.
Could I use them to count the RNA editing sites in Alu, non-Alu and non-repeat region? 

Thanks.

**Comment by jumphone** [comment]
The latest version of SPRINT will do another round of clustering after combining SNVs from different region (Alu, nalurp, and nrp). If you don’t want to use this part of additional RES, you can count the RES using these three files.

Best,

Feng

**Comment by mt831** [comment]
Thank you. I used the three files regular_alu.res, regular_nalurp.res and regular_nrp.res. But I noticed that the sum of the three files is not equal to the number of RNA editing sites in SPRINT_identified_all.res file.

**Comment by mt831** [comment]
Thank you. 
I used the files regular_alu.res, regular_nalurp.res ,regular_nrp. But I noticed that the sum of these files is not equal to the number of RNA editing sites in SPRINT_identified_regular.res file.

**Comment by jumphone** [comment]
The additional RESs in "SPRINT_identified_regular.res" are identified by clustering after combining SNVs from different regions.
