### ISSUE TITLE
How to add the repeat file into the command?  

### ISSUE THREAD

**Issue by duanshumeng** [jumphone/SPRINT#8]
nohup sprint main -c 6 -rp Triplophysarosa.repeat.txt -1 Fish-A808-T01_good_1.fq -2 Fish-A808-T01_good_2.fq Triplophysarosa.fa  Fish-A808-T01-main-rptxt /data/duanshumeng/biosoft/bwa-0.7.15/bwa /data/duanshumeng/biosoft/samtools-1.2/samtools &

This is my command.If there is no  "-rp Triplophysarosa.repeat.txt " ,it worked well .However,when I add that cannot run properly.I fail to  download your hg19_repeat.txt many times.

**Comment by jumphone** [comment]
Hi, you have two options:
1. Download repeat files from [https://sourceforge.net/projects/sprintpy/files/dbRES/](url)
2. Try to follow the workflow in [https://github.com/jumphone/SPRINT#4-change-repeatmasker-file-rmsk-into-bed-file-used-by-sprint](url)

**Comment by mt831** [comment]
Hi, It seems the link  is dead. Any other ways to download the repeat files ?
Thank you.

**Comment by jumphone** [comment]
> Hi, It seems the link is dead. Any other ways to download the repeat files ?
> Thank you.

Please use the new download webpage: 
https://sourceforge.net/projects/sprintpy/files/dbRES/

Thanks,
Feng
