### ISSUE TITLE
[W::sam_read1] parse error at line 1

### ISSUE THREAD

**Issue by Najierida** [jumphone/SPRINT#9]
hi Jumphone, 
when i run "sprint main",  i met the error as below:
[huang@node6 sle2]$ mapping...
[W::sam_read1] parse error at line 1
[main_samview] truncated file.
[W::sam_read1] parse error at line 1
[main_samview] truncated file.
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
...

[W::sam_read1] parse error at line 1
[main_samview] truncated file.

and there are my script:
sprint main  
-rp /home/sprint_ref/hg19_repeat.txt 
-c 6 -p 2 -1 /home/sprint_ref/SRR1643011_1.fq -2 /home/sprint_ref/SRR1643011_2.fq 
/home/sprint_ref/hg19.fa  
/home/huang/SLE/sle2 
/home/huang/analysispipeline/simulation-programs/bwa-0.6.1/bwa 
/home/huang/installed/sinotools/thirdparty/samtools/samtools-1.3.1/samtools

then there is no output. I've checked the .repeat file, the .fa file, the path to bwa and samtools. 
Thank you.

**Comment by jumphone** [comment]
please try to use samtools==1.2

**Comment by Najierida** [comment]
Thank you for the  reply which is useful, samtools 1.2 worked well.
then it give report as below:

preprocessing...
mapping...
identifying SNVs...
identifying RESs...
finished !
Call RESs done in 18.09.23:12:12
SRR3362713 Start calling RESs in 18.09.23:12:29
[bwa_aln] 17bp reads: max_diff = 2
....
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln] fail to locate the index
[bwa_aln] fail to locate the index
[bwa_sai2sam_se] fail to locate the index
[bwa_sai2sam_se] fail to locate the index
[bwa_aln] 17bp reads: max_diff = 2
....
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln] fail to locate the index
[bwa_sai2sam_se] fail to locate the index

it still give no output result.
which index does it require? should I use bwa to build a index at first?

Thank you.

**Comment by jumphone** [comment]
please use “sprint prepare” to build the index

**Comment by Najierida** [comment]
Maybe sth wrong with the copy of the .repeat file. when i use the original one, it goes well. thank you.
